### ISSUE TITLE
Fails with Gtk3 requires X11, and no DISPLAY environment variable is set

### ISSUE THREAD

**Issue by ieugen** [gnome-keysign/gnome-keysign#104]
Hi,

I installed the app from https://flathub.org/apps/details/org.gnome.Keysign and I get this:

```
$ flatpak run org.gnome.Keysign 
Traceback (most recent call last):
  File "/app/bin/gnome-keysign", line 10, in <module>
    sys.exit(main())
  File "/app/lib/python3.7/site-packages/keysign/__init__.py", line 22, in main
    from . import app
  File "/app/lib/python3.7/site-packages/keysign/app.py", line 31, in <module>
    from twisted.internet import gtk3reactor
  File "/app/lib/python3.7/site-packages/twisted/internet/gtk3reactor.py", line 38, in <module>
    "Gtk3 requires X11, and no DISPLAY environment variable is set")
ImportError: Gtk3 requires X11, and no DISPLAY environment variable is set
```

I was able to fix it by using Flatseal and removing `socket=wayland` permission. 

```
Linux daos-495 5.7.0-1-amd64 #1 SMP Debian 5.7.6-1 (2020-06-24) x86_64 GNU/Linux
```

**Comment by muelli** [comment]
I remember having seen this before. I also remember that we tried to file a bug against Twisted. I don't remember, though, whether we succeeded. Have you tried to file a bug?

**Comment by ieugen** [comment]
Hi, 

No, I filed a bug here because this is the version I installed. 
I don't know anything about Twisted.
I hope this helps someone find a solution or at least a workaround.
A simple thing could be to disable `socket=wayland` on default install.

**Comment by muelli** [comment]
yeah, I see. Thanks for documenting a way to make it work.

This is a bug in Twisted, though. Disabling the Wayland socket is only a mildly entertaining workaround that will break down once Wayland is popular enough to warrant enabling it again.
So the Twisted people will need to be made aware of this problem.
@RyuzakiKK do you remember whether and what we did?

**Comment by RyuzakiKK** [comment]
> yeah, I see. Thanks for documenting a way to make it work.
> 
> This is a bug in Twisted, though. Disabling the Wayland socket is only a mildly entertaining workaround that will break down once Wayland is popular enough to warrant enabling it again.
> So the Twisted people will need to be made aware of this problem.
> @RyuzakiKK do you remember whether and what we did?

The bug was this one https://github.com/flathub/org.gnome.Keysign/issues/14
In the end I think that nobody opened yet the bug upstream against Twisted.

**Comment by muelli** [comment]
the upstream bug is https://twistedmatrix.com/trac/ticket/9904
I wonder whether reverting the offending commit, https://github.com/twisted/twisted/commit/4142aeeb6e490e4804a555e2c1097f02d9a4d055, would work. hm.

**Comment by muelli** [comment]
I have tested on a Wayland session and it seems as if the DISPLAY variable doesn't matter when run under pure Wayland. Reverting the whole commit seems like a bit too big, but at least the offending test can be patched out.

For the flathub build, we could write a small wrapper that sets the variable in case it is not set.

**Comment by muelli** [comment]
https://github.com/twisted/twisted/pull/1379

**Comment by muelli** [comment]
I believe this is fixed since Twisted does not raise this error any more.
