### ISSUE TITLE
programming error detected

### ISSUE THREAD

**Issue by bintonw** [gnome-keysign/gnome-keysign#114]
### Description

Give this report a short descriptive title. Use something like "{feature-that-broke}: {what-went-wrong}" for the title, if you can. Then please replace this text with a longer description of the bug. Screenshots or videos are great, too!

#### Steps to reproduce

Please tell us what you were doing when the error message popped up. If you can provide step-by-step instructions on how to reproduce the bug, that's even better.

#### Traceback

```python
System information: Linux-5.4.0-96-generic-x86_64-with-Peppermint-10-bionic
Python information: 2.7.17 (default, Feb 27 2021, 15:10:58) 
[GCC 7.5.0]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/keysign/scan_barcode.py", line 142, on_map(self=<scan_barcode.BarcodeReaderGTK object at 0x7f862...scan_barcode+BarcodeReaderGTK at 0x5646d3d59f90)>, *args=(<scan_barcode.BarcodeReaderGTK object at 0x7f862...scan_barcode+BarcodeReaderGTK at 0x5646d3d59f90)>,), **kwargs={})
            '''It seems this is called when the widget is becoming visible'''
            self.run()
  variables: {'self.run': ('local', <bound method BarcodeReaderGTK.run of <scan_barcode.BarcodeReaderGTK object at 0x7f86265dfb90 (keysign+scan_barcode+BarcodeReaderGTK at 0x5646d3d59f90)>>)}
  File "/usr/lib/python2.7/dist-packages/keysign/scan_barcode.py", line 113, run(self=<scan_barcode.BarcodeReaderGTK object at 0x7f862...scan_barcode+BarcodeReaderGTK at 0x5646d3d59f90)>)
            log.info("Launching pipeline %s", pipeline)
            pipeline = Gst.parse_launch(pipeline)
  variables: {'pipeline': ('local', 'autovideosrc  \n ! tee name=t \n       t. ! queue ! videoconvert \n                  ! zbar cache=true attach_frame=true \n                  ! fakesink \n       t. ! queue ! videoconvert \n                 ! gtksink sync=false name=imagesink enable-last-sample=false \n'), 'Gst.parse_launch': ('global', gi.FunctionInfo(parse_launch))}
Error: gst_parse_error: no element "gtksink" (1)
```

**Comment by muelli** [comment]
Thanks for your report!
How did you install the application?
It seems that a dependency is missing.

**Comment by bintonw** [comment]
Installed the package via APT.
Checked dependency list & seems to been ok now.
Your assistance is appreciated.

**Comment by muelli** [comment]
can you show me the output of `apt policy gnome-keysign`? And.. maybe... `lsb_release -a`

**Comment by muelli** [comment]
thanks for your reply!
The version you're using is quite old :-/ And it appears to be wrongly packaged. Or rather, the dependencies seems to be a problem. The "gtksink" element seems to be missing. You can try to find it by running something like `gst-inspect-1.0 gtksink` or simply `gst-inspect  gtksink`. If you don't see the element, then you need to ask your distribution to provide it to you, somehow :-/

If you can run flatpaks, then you may be able to run a current version from flathub.

**Comment by muelli** [comment]
Let me close this here as a packaging problem.
