### ISSUE TITLE
Invalid appdata.xml file installed

### ISSUE THREAD

**Issue by DimStar77** [gnome-keysign/gnome-keysign#26]
While processing the built RPM's with appstream-builder (in order to get full AS info for a repo), as-builder complains about gnome-keysign having invalid metadata:

```
(appstream-builder:20325): As-WARNING **: ignoring description '<description><_p>GNOME-Keysign allows signing OpenPGP keys comfortably.</_p><_p>It can scan another key's barcode and transfer the key securely, allowing for casual two-party key signing sessions. It follows best practises by sending the encrypted signatures to the UIDs of a key using the Email client the user configured to use.</_p></description>' from ./tmp/gnome-keysign-0.9.5-18.1/usr/share/appdata/gnome-keysign.appdata.xml: Unknown tag '_p'
```

Seems the appdata.xml file is prepared for translation, but is not processed completely, installing invalid XML into the actual system.

**Comment by muelli** [comment]
right. good catch. We're working on it with the translation efforts. https://github.com/gnome-keysign/gnome-keysign/pull/27 should fix this issue.

**Comment by muelli** [comment]
`appstream-cli` validates the installed file now. I think this issue is resolved.  Let's wait for the RPM builder though. Maybe it complains still.
