### ISSUE TITLE
document better all the awesome features

### ISSUE THREAD

**Issue by anarcat** [gnome-keysign/gnome-keysign#30]
I have been following the development of gnome-keysign for a while now, and coming back to this webpage is underwhelming. I *know* there are tons of awesome things this project does, but those are not explained in the README, nor in the [wiki page](https://wiki.gnome.org/Apps/Keysign). For example, Keysign supports using avahi and a local webserver to exchange keys. This is alluded to in the README, but not stated clearly.

Also, I believe the README makes no mention of qrcode transfers.

A "Features" section would be, therefore, a great idea.

Thanks!

**Comment by muelli** [comment]
Heh. I think it's a good idea. The readme needs updates, anyway. For example, a MAC is used to authenticate the key.  But I'm a bit puzzled what we could list as features though. Bluetooth transfer comes to mind. But what else?

**Comment by anarcat** [comment]
well, you're in a better position to document this than me, but i can give it a shot:

 * avahi-based local network key exchange
 * bluetooth support
 * MAC key authentication
 * qrcode scanning with anti-spoofing mechanisms (i assume you outline the scanned qrcode?)
 * manual fingerprint verification
 * signed user IDs encrypted and individually sent to verify email ownership
 * reuses existing email clients with `xdg-email`
 * GTK3 GUI

anything else i'm forgetting?

maybe it would be useful to regroup those as well... e.g. "multiple key authentication methods ..."

**Comment by muelli** [comment]
let me know what you think of 025cec774abe926a38700eacef0e8444d1fc7d68?
