### ISSUE TITLE
[RFE] use python-six for py2/py3 handling

### ISSUE THREAD

**Issue by ignatenkobrain** [gnome-keysign/gnome-keysign#4]
There's no reason to not use it since it's brought up already by one of dependencies..

**Comment by muelli** [comment]
There is at least one reason: It needs someone to actually write the patches ;-)
I'm happily accepting patches.
I think we're good so far, though.
I'm inclined to close this issue in favour of https://github.com/gnome-keysign/gnome-keysign/issues/3.

**Comment by muelli** [comment]
we should be python3 compatible. Please file a bug if that's not the case.
