### ISSUE TITLE
Appdata XML shipped in nonstandard location

### ISSUE THREAD

**Issue by satta** [gnome-keysign/gnome-keysign#49]
According to https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Application.html the `.appdata.xml` files should be shipped in `/usr/share/metainfo/`, not in `/usr/share/appdata`.
See https://github.com/gnome-keysign/gnome-keysign/blob/master/setup.py#L195.

**Comment by RyuzakiKK** [comment]
Thanks. I just opened a PR that fixes the appdata location.
