### ISSUE TITLE
Mark subject and body as translatable

### ISSUE THREAD

**Issue by RyuzakiKK** [gnome-keysign/gnome-keysign#61]
In util.py right now the email subject and body are not marked as translatable, but they definitely should be https://github.com/gnome-keysign/gnome-keysign/blob/master/keysign/util.py#L204

In order to mark them, the library i18n needs to be used. Examples of how to do it are all over this repository.
Here there are the instructions to test if the fix is working https://github.com/gnome-keysign/gnome-keysign/tree/master/keysign/locale

**Comment by mdew192837** [comment]
I can do this

**Comment by muelli** [comment]
Hm. I'm not entirely convinced that this is a good idea.  My main objection is that I cannot read, say, Italian. Maybe a bi-lingual email would be good, then. But even then, the user is not suppose to see this email. Ever. AFAIR, it's encrypted with the recipient's key s.t. the user is not even able to read it. So why would you send the email in your own language?

**Comment by mdew192837** [comment]
So don't do this yet? @muelli

**Comment by RyuzakiKK** [comment]
My assumption was that the probability that the two users were able to speak the same language was very high. Because they need to met in real life, unless they are like in an international conference or something similar.
Even there, they can manually edit the email before sending it.

All this is due to the fact that we can't do assumptions on the recipient's language. Ok that English should be the lingua franca here, but still not everyone are able to read it.

**Comment by RyuzakiKK** [comment]
Done with #62
