### ISSUE TITLE
error in french translation

### ISSUE THREAD

**Issue by anarcat** [gnome-keysign/gnome-keysign#78]
The first window in the gnome-keysign GUI says: "Sélectionnez une clé à signer" and then lists my own private keys. This translates to "Select a key to sign" when translated word by word, but a better translation of what it means would be "Select the key to sign", which I interpret as the key I will sign, not the key I will sign *with*.

I'm not sure what a better translation would be, but that's definitely ambiguous and confusing. I would maybe say "Sélectionnez la clé avec laquelle vous voulez signer une autre clé" but that's kind of a mouthful...

**Comment by muelli** [comment]
wow, that's incredibly useful. Merci beaucoup. These days we should have translator comments working. It'd be a nice hint for the translators to know what the intended semantic is, so we should provide a comment that expresses our intention of using the certifying key rather than the key to be signed.

**Comment by anarcat** [comment]
after talking to a fellow french speaker, he suggested "Sélectionnez votre clef de signature principale" (ie. "Select your main signing key"). I'm not sure about the "principale" ("main") part, but it is certainly less ambiguous.

Just for the record, I believe monkeysign has the exact same bug, for the exact same reason (lack of context). :)

**Comment by muelli** [comment]
Thanks!
This should be fixed with b291cc84437506f2c843dd7474bea64de08cb0eb

**Comment by anarcat** [comment]
hmm... but not the french translation itself?

**Comment by RyuzakiKK** [comment]
@anarcat we handle the translations from GNOME Damned Lies. So probably the best way to fix the French translation is by leaving a comment there https://l10n.gnome.org/vertimus/gnome-keysign/master/locale/fr/

**Comment by muelli** [comment]
Right, I think the translation is correct, though.
The key the user chooses is the one we want to have signed by someone else.
We don't give the user the option to select their own key to be used for signing someone else's key.
