### ISSUE TITLE
"here" is not good for link text

### ISSUE THREAD

**Issue by scootergrisen** [gnome-keysign/gnome-keysign#82]
"here" is not good text for links.
https://github.com/gnome-keysign/gnome-keysign/blob/8e370dbed450956a3a7db0c281b295e1ed8def49/keysign/receive.ui#L53-L56

Better to have the text be what the user can expect to find.
Like the same title as the page: "No GNOME Keysign servers around".

Then change the string so "No GNOME Keysign servers around" is not there twice if you use that text.

**Comment by muelli** [comment]
thanks for your input. Just to be clear.
Are you suggesting to use "No GNOME Keysign servers around" as the hyperlink text?

**Comment by scootergrisen** [comment]
Yes because that is was it says on the page.

**Comment by muelli** [comment]
thanks.  Do you fancy cooking up a small patch?  It should even be possible through the Github Web editor.

**Comment by scootergrisen** [comment]
Maybe a bit silly it says "No GNOME Keysign servers around" twice now but.

**Comment by scootergrisen** [comment]
I have not used the software yet just translated it.
Maybe change the first line of text with the smiley at the end to something else.

**Comment by muelli** [comment]
changed with 99679c7

Thanks!
