### ISSUE TITLE
Use placeholder instead of "(C)" for translators

### ISSUE THREAD

**Issue by scootergrisen** [gnome-keysign/gnome-keysign#83]
Instead of "(C)" in these two strings used in po files:

    Translated for gettext (C)
    Translated for Python (C)

https://github.com/gnome-keysign/gnome-keysign/blob/cdd747788832ea883ca838e4e7400ce0f007ea24/keysign/i18n.py#L39-L47

Maybe better to use placeholders like "(%s)" or whatever can be used and autofill the content.
Like using the valve from the po header ("Language: \n").

I see some translation have translated incorrectly:
https://github.com/gnome-keysign/gnome-keysign/blob/fb9b163d61673ece4c5411297db2945f56692eb6/keysign/locale/cs/LC_MESSAGES/keysign.po#L229
https://github.com/gnome-keysign/gnome-keysign/blob/2b06ed6b98eda1b0c16445ee0043456e765ec0ea/keysign/locale/fr/LC_MESSAGES/keysign.po#L234

**Comment by muelli** [comment]
cool. Should be fixed with cf5547e. Thanks!
