### ISSUE TITLE
Remove space before "..."

### ISSUE THREAD

**Issue by scootergrisen** [gnome-keysign/gnome-keysign#84]
Perhaps remove space before "..." in https://github.com/gnome-keysign/gnome-keysign/blob/8e370dbed450956a3a7db0c281b295e1ed8def49/keysign/receive.ui#L226
So "..." is the same as in the other strings in the translations.

    msgid "Search Tracker..."
    msgid "Report..."
    msgid "Details..."
    msgid "Downloading key-data. Please wait ..."

**Comment by muelli** [comment]
Cool. Thanks. Should be fixed with b971e94
