### ISSUE TITLE
Remove "-" from "GNOME-Keysign"

### ISSUE THREAD

**Issue by scootergrisen** [gnome-keysign/gnome-keysign#85]
Maybe remove "-" from "GNOME-Keysign" in this string:

    GNOME-Keysign allows signing OpenPGP keys comfortably and securely
    via the local network or Bluetooth.

https://github.com/gnome-keysign/gnome-keysign/blob/eaee3c48a870b5bb7d9e4645684fb149ec56dcf2/data/org.gnome.Keysign.raw.appdata.xml#L11

**Comment by muelli** [comment]
good call! Thanks!
Should be fixed with 746ba08c02b559c9eec2a4d54630dc4e9a5cc538
